spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pdl?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: cf
    password: cf
    driver-class-name: com.mysql.jdbc.Driver

server:
  context-path: /demo
  port: 8080
